%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_HeuristicHazard
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2007-12-04_15/otp_src_R12B-0/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.16
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_HeuristicHazard').
-ic_compiled("4_2_16").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/HeuristicHazard:1.0",
                   "HeuristicHazard",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/HeuristicHazard:1.0".

%% returns name
name() -> "CosTransactions_HeuristicHazard".



