%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_NoTransaction
%% Source: /ldisk/daily_build/otp_prebuild_r11b.2007-06-11_19/otp_src_R11B-5/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.13
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_NoTransaction').
-ic_compiled("4_2_13").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/NoTransaction:1.0",
                   "NoTransaction",
                   []}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/NoTransaction:1.0".

%% returns name
name() -> "CosTransactions_NoTransaction".



