%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_SynchronizationUnavailable
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-09-02_20/otp_src_R12B-4/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.18
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_SynchronizationUnavailable').
-ic_compiled("4_2_18").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/SynchronizationUnavailable:1.0",
                   "SynchronizationUnavailable",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/SynchronizationUnavailable:1.0".

%% returns name
name() -> "CosTransactions_SynchronizationUnavailable".



