%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_HeuristicRollback
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-06-10_20/otp_src_R12B-3/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.18
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_HeuristicRollback').
-ic_compiled("4_2_18").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/HeuristicRollback:1.0",
                   "HeuristicRollback",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/HeuristicRollback:1.0".

%% returns name
name() -> "CosTransactions_HeuristicRollback".



