%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: mnesia_corba_session
%% Source: /ldisk/daily_build/otp_prebuild_r11b.2007-06-11_19/otp_src_R11B-5/lib/mnesia_session/src/mnesia_corba_session.idl
%% IC vsn: 4.2.13
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(MNESIA_CORBA_SESSION_HRL).
-define(MNESIA_CORBA_SESSION_HRL, true).




-endif.


