%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_SequenceProxyPushSupplier
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13a.2009-03-16_22/otp_src_R13A/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_SEQUENCEPROXYPUSHSUPPLIER_HRL).
-define(COSNOTIFYCHANNELADMIN_SEQUENCEPROXYPUSHSUPPLIER_HRL, true).




-endif.


