%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_ProxyConsumer
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-06-10_20/otp_src_R12B-3/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.18
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_PROXYCONSUMER_HRL).
-define(COSNOTIFYCHANNELADMIN_PROXYCONSUMER_HRL, true).




-endif.


