%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_ProxyPushConsumer
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-04-07_20/otp_src_R12B-1/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.17
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_PROXYPUSHCONSUMER_HRL).
-define(COSNOTIFYCHANNELADMIN_PROXYPUSHCONSUMER_HRL, true).




-endif.


