%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_SequencePushConsumer
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b01.2009-06-07_20/otp_src_R13B01/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.21
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_SEQUENCEPUSHCONSUMER_HRL).
-define(COSNOTIFYCOMM_SEQUENCEPUSHCONSUMER_HRL, true).




-endif.


