%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_SequencePullConsumer
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-04-07_20/otp_src_R12B-1/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.17
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_SEQUENCEPULLCONSUMER_HRL).
-define(COSNOTIFYCOMM_SEQUENCEPULLCONSUMER_HRL, true).




-endif.


