%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyFilter_MappingFilter
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13b.2009-04-20_20/otp_src_R13B/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYFILTER_MAPPINGFILTER_HRL).
-define(COSNOTIFYFILTER_MAPPINGFILTER_HRL, true).




-endif.


