%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-02-05_20/otp_src_R12B-1/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.16
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_HRL).
-define(COSNOTIFYCOMM_HRL, true).


-record('CosNotifyComm_InvalidEventType', {'OE_ID'="IDL:omg.org/CosNotifyComm/InvalidEventType:1.0", type}).


-endif.


