%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyComm
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13a.2009-03-16_22/otp_src_R13A/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYCOMM_HRL).
-define(OE_COSNOTIFYCOMM_HRL, true).




-endif.


