%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventComm_Disconnected
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-11-05_12/otp_src_R12B-5/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.19
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventComm_Disconnected').
-ic_compiled("4_2_19").


-include("CosEventComm.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventComm/Disconnected:1.0","Disconnected",
                   []}.

%% returns id
id() -> "IDL:omg.org/CosEventComm/Disconnected:1.0".

%% returns name
name() -> "CosEventComm_Disconnected".



