#ifndef _EVENT_CHANNEL_FACTORY_IDL
#define _EVENT_CHANNEL_FACTORY_IDL

#include "OrberEventChannelAdmin.idl"

#pragma prefix "omg.org"

module OrberEventChannel
{
  interface EventChannelFactory
  {
     OrberEventChannelAdmin::EventChannel create_event_channel();
 };
};

#endif


