%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cosEventApp
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-04-07_20/otp_src_R12B-1/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.2.17
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTAPP_HRL).
-define(OE_COSEVENTAPP_HRL, true).




-endif.


