%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm_PullerS
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-02-05_20/otp_src_R12B-1/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.2.16
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_PULLERS_HRL).
-define(OE_COSEVENTCOMM_PULLERS_HRL, true).




-endif.


