%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm_Channel
%% Source: /ldisk/daily_build/otp_prebuild_r11b.2007-06-11_19/otp_src_R11B-5/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.2.13
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_CHANNEL_HRL).
-define(OE_COSEVENTCOMM_CHANNEL_HRL, true).




-endif.


