%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosFileTransfer
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13b.2009-04-15_20/otp_src_R13B/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosFileTransfer').
-ic_compiled("4_2_20").


%% Interface functions
-export(['FTAM_1'/0, 'FTAM_2'/0, 'FTAM_3'/0]).
-export(['FTAM_4'/0, 'FTAM_5'/0, 'NBS_9'/0]).
-export(['INTAP_1'/0]).

%%%% Constant: 'FTAM_1'
%%
'FTAM_1'() -> 1.

%%%% Constant: 'FTAM_2'
%%
'FTAM_2'() -> 2.

%%%% Constant: 'FTAM_3'
%%
'FTAM_3'() -> 3.

%%%% Constant: 'FTAM_4'
%%
'FTAM_4'() -> 4.

%%%% Constant: 'FTAM_5'
%%
'FTAM_5'() -> 5.

%%%% Constant: 'NBS_9'
%%
'NBS_9'() -> 6.

%%%% Constant: 'INTAP_1'
%%
'INTAP_1'() -> 7.

