#!/bin/sh

rm -f $1-plot

for n in 0 1 2 3; do
  REPS=10 time -o $1.tmp -f "%U" ./runtests-$n > /dev/null
  REPS=10 time -a -o $1.tmp -f "%U" ./runtests-$n > /dev/null
  REPS=10 time -a -o $1.tmp -f "%U" ./runtests-$n > /dev/null

  echo "timed runtests-$n user time (stresses NFA-based implementations)" > $1-$n
  cat $1.tmp >> $1-$n
  echo "2 k + + 3 / p" >> $1.tmp
  echo -n "average: " >> $1-$n
  dc < $1.tmp >> $1-$n
  echo -n $n "  " >> $1-plot
  dc < $1.tmp >> $1-plot
  rm -f $1.tmp
done
