%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_FilterNotFound
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2007-12-04_15/otp_src_R12B-0/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.16
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_FilterNotFound').
-ic_compiled("4_2_16").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/FilterNotFound:1.0",
                   "FilterNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/FilterNotFound:1.0".

%% returns name
name() -> "CosNotifyFilter_FilterNotFound".



