%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_ConnectionAlreadyInactive
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b01.2009-06-07_20/otp_src_R13B01/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.21
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_ConnectionAlreadyInactive').
-ic_compiled("4_2_21").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/ConnectionAlreadyInactive:1.0",
                   "ConnectionAlreadyInactive",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/ConnectionAlreadyInactive:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_ConnectionAlreadyInactive".



