%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_AdminNotFound
%% Source: /ldisk/daily_build/otp_prebuild_r11b.2007-06-11_19/otp_src_R11B-5/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.13
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_AdminNotFound').
-ic_compiled("4_2_13").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/AdminNotFound:1.0",
                   "AdminNotFound",
                   []}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/AdminNotFound:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_AdminNotFound".



