%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_UnsupportedFilterableData
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b02.2009-09-21_11/otp_src_R13B02/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.22
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_UnsupportedFilterableData').
-ic_compiled("4_2_22").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/UnsupportedFilterableData:1.0",
                   "UnsupportedFilterableData",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/UnsupportedFilterableData:1.0".

%% returns name
name() -> "CosNotifyFilter_UnsupportedFilterableData".



