%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_InvalidGrammar
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-09-02_20/otp_src_R12B-4/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.18
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_InvalidGrammar').
-ic_compiled("4_2_18").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/InvalidGrammar:1.0",
                   "InvalidGrammar",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/InvalidGrammar:1.0".

%% returns name
name() -> "CosNotifyFilter_InvalidGrammar".



