%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_NotConnected
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-09-02_20/otp_src_R12B-4/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.18
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_NotConnected').
-ic_compiled("4_2_18").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/NotConnected:1.0",
                   "NotConnected",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/NotConnected:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_NotConnected".



