%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_ConstraintNotSupported
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13a.2009-03-16_22/otp_src_R13A/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_ConstraintNotSupported').
-ic_compiled("4_2_20").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/ConstraintNotSupported:1.0",
                   "ConstraintNotSupported",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/ConstraintNotSupported:1.0".

%% returns name
name() -> "CosPropertyService_ConstraintNotSupported".



