%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_PropertyTypes
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13b.2009-04-15_20/otp_src_R13B/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_PropertyTypes').
-ic_compiled("4_2_20").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,tk_TypeCode,0}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/PropertyTypes:1.0".

%% returns name
name() -> "CosPropertyService_PropertyTypes".



