%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_PropertyNotFound
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-11-05_12/otp_src_R12B-5/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.19
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_PropertyNotFound').
-ic_compiled("4_2_19").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/PropertyNotFound:1.0",
                   "PropertyNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/PropertyNotFound:1.0".

%% returns name
name() -> "CosPropertyService_PropertyNotFound".



