%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_FixedProperty
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-06-10_20/otp_src_R12B-3/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.18
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_FixedProperty').
-ic_compiled("4_2_18").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/FixedProperty:1.0",
                   "FixedProperty",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/FixedProperty:1.0".

%% returns name
name() -> "CosPropertyService_FixedProperty".



