%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventDomainAdmin_DomainNotFound
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b02.2009-09-21_11/otp_src_R13B02/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.2.22
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventDomainAdmin_DomainNotFound').
-ic_compiled("4_2_22").


-include("CosEventDomainAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventDomainAdmin/DomainNotFound:1.0",
                   "DomainNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventDomainAdmin/DomainNotFound:1.0".

%% returns name
name() -> "CosEventDomainAdmin_DomainNotFound".



