%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContext_AlreadyBound
%% Source: /ldisk/daily_build/otp_prebuild_r11b.2007-06-11_19/otp_src_R11B-5/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.2.13
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContext_AlreadyBound').
-ic_compiled("4_2_13").


-include("CosNaming_NamingContext.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0",
                   "AlreadyBound",
                   []}.

%% returns id
id() -> "IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0".

%% returns name
name() -> "CosNaming_NamingContext_AlreadyBound".



