%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContextExt_AlreadyBound
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-02-05_20/otp_src_R12B-1/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.2.16
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContextExt_AlreadyBound').
-ic_compiled("4_2_16").


-include("CosNaming_NamingContextExt.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0",
                   "AlreadyBound",[]}.

%% returns id
id() -> "IDL:CosNaming/NamingContextExt/AlreadyBound:1.0".

%% returns name
name() -> "CosNaming_NamingContextExt_AlreadyBound".



