%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContext_InvalidName
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13a.2009-03-16_22/otp_src_R13A/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContext_InvalidName').
-ic_compiled("4_2_20").


-include("CosNaming_NamingContext.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0",
                   "InvalidName",[]}.

%% returns id
id() -> "IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0".

%% returns name
name() -> "CosNaming_NamingContext_InvalidName".



