#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp disable

main(Args) ->
    io:format("Root dir: ~s\n", [code:root_dir()]),
    io:format("Script args: ~p\n", [Args]),
    io:format("Emu arg: ~p\n", [init:get_argument(smp)]).
