%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PushSupplier
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b02.2009-09-21_11/otp_src_R13B02/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.22
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PUSHSUPPLIER_HRL).
-define(COSEVENTCOMM_PUSHSUPPLIER_HRL, true).




-endif.


