%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPullConsumer
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-02-05_20/otp_src_R12B-1/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.16
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPULLCONSUMER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPULLCONSUMER_HRL, true).




-endif.


