%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13a.2009-03-16_22/otp_src_R13A/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_HRL).
-define(COSEVENTCOMM_HRL, true).


-record('CosEventComm_Disconnected', {'OE_ID'="IDL:omg.org/CosEventComm/Disconnected:1.0"}).


-endif.


