%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2007-12-04_15/otp_src_R12B-0/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.16
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_HRL).
-define(COSEVENTCOMM_HRL, true).


-record('CosEventComm_Disconnected', {'OE_ID'="IDL:omg.org/CosEventComm/Disconnected:1.0"}).


-endif.


