%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PullConsumer
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13b.2009-04-20_20/otp_src_R13B/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PULLCONSUMER_HRL).
-define(COSEVENTCOMM_PULLCONSUMER_HRL, true).




-endif.


