%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPullConsumer
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b01.2009-06-07_20/otp_src_R13B01/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.21
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPULLCONSUMER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPULLCONSUMER_HRL, true).




-endif.


