%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: m
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b02.2009-09-21_11/otp_src_R13B02/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.2.22
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(M_HRL).
-define(M_HRL, true).


-record(m_NotAnInteger, {'OE_ID'="IDL:m/NotAnInteger:1.0"}).


-endif.


