%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_ex
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13b.2009-04-15_20/otp_src_R13B/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_EX_HRL).
-define(OE_EX_HRL, true).




-endif.


