%%  Warning: Do not edit this file.  It was automatically
%%  generated by 'beam_makeops' on Tue Jun 10 20:30:59 2008.

-define(tag_u, 0).
-define(tag_i, 1).
-define(tag_a, 2).
-define(tag_x, 3).
-define(tag_y, 4).
-define(tag_f, 5).
-define(tag_h, 6).
-define(tag_z, 7).

