#=============================================================================
#
#    File:  lib/typer/Makefile
# Authors:  Bingwen He, Tobias Lindahl, and Kostis Sagonas
#
#=============================================================================
include $(ERL_TOP)/make/target.mk
include $(ERL_TOP)/make/$(TARGET)/otp.mk

#
# Macros
#

SUB_DIRECTORIES = src

include vsn.mk
VSN = $(TYPER_VSN)

SPECIAL_TARGETS =

#
# Default Subdir Targets
#
include $(ERL_TOP)/make/otp_subdir.mk

