%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTime_TimeUnavailable
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-06-10_20/otp_src_R12B-3/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.18
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTime_TimeUnavailable').
-ic_compiled("4_2_18").


-include("CosTime.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTime/TimeUnavailable:1.0",
                   "TimeUnavailable",[]}.

%% returns id
id() -> "IDL:omg.org/CosTime/TimeUnavailable:1.0".

%% returns name
name() -> "CosTime_TimeUnavailable".



