%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent_TimerEventService
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-04-07_20/otp_src_R12B-1/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.2.17
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_TIMEREVENTSERVICE_HRL).
-define(COSTIMEREVENT_TIMEREVENTSERVICE_HRL, true).




-endif.


