%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent_TimerEventHandler
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-02-05_20/otp_src_R12B-1/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.2.16
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_TIMEREVENTHANDLER_HRL).
-define(COSTIMEREVENT_TIMEREVENTHANDLER_HRL, true).




-endif.


