%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_TimeBase
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b01.2009-06-07_20/otp_src_R13B01/lib/cosTime/src/TimeBase.idl
%% IC vsn: 4.2.21
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_TIMEBASE_HRL).
-define(OE_TIMEBASE_HRL, true).




-endif.


