%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: TimeBase
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-11-05_12/otp_src_R12B-5/lib/cosTime/src/TimeBase.idl
%% IC vsn: 4.2.19
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(TIMEBASE_HRL).
-define(TIMEBASE_HRL, true).


-record('TimeBase_UtcT', {time, inacclo, inacchi, tdf}).
-record('TimeBase_IntervalT', {lower_bound, upper_bound}).


-endif.


