#-*-makefile-*-   ; force emacs to enter makefile-mode

# ``The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved via the world wide web at http://www.erlang.org/.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# The Initial Developer of the Original Code is Ericsson Utvecklings AB.
# Portions created by Ericsson are Copyright 1999, Ericsson Utvecklings
# AB. All Rights Reserved.''
# 
#     $Id$
#

include rules.mk

# ----------------------------------------------------
# Target Specs
# ----------------------------------------------------

CP = cp
DATADIR = inets_SUITE_data

ifeq ($(INETS_DATA_DIR),)
INETS_DATA_DIR = ./inets_SUITE_data
endif

ifeq ($(INETS_PRIV_DIR),)
# INETS_PRIV_DIR = /ldisk/tests/bmk/inets/priv_dir
INETS_PRIV_DIR = /tmp/inets/priv_dir
endif

INETS_FLAGS = -Dinets_data_dir='"$(INETS_DATA_DIR)"' \
              -Dinets_priv_dir='"$(INETS_PRIV_DIR)"'

### 
### test suite debug flags
### 
ifeq ($(FTP_DEBUG_CLIENT),)
  FTP_DEBUG_CLIENT = y
endif

ifeq ($(FTP_DEBUG_CLIENT),y)
  FTP_FLAGS += -Dftp_debug_client
endif

ifeq ($(FTP_DEBUG),)
  FTP_DEBUG = d
endif

ifeq ($(FTP_DEBUG),l)
  FTP_FLAGS += -Dftp_log
endif

ifeq ($(FTP_DEBUG),d)
  FTP_FLAGS += -Dftp_debug -Dftp_log
endif

ifeq ($(INETS_DEBUG),)
  INETS_DEBUG = d
endif

ifeq ($(INETS_DEBUG),l)
  INETS_FLAGS += -Dinets_log
endif

ifeq ($(INETS_DEBUG),d)
  INETS_FLAGS += -Dinets_debug -Dinets_log
endif


### 
### HTTPD verbosity flags
### 

ifneq ($(MANV),)
  INETS_FLAGS += -Dhttpd_manager_verbosity=$(MANV)
else
  INETS_FLAGS += -Dhttpd_manager_verbosity=log
endif

ifneq ($(REQV),)
  INETS_FLAGS += -Dhttpd_request_handler_verbosity=$(REQV)
else
  INETS_FLAGS += -Dhttpd_request_handler_verbosity=log
endif

ifneq ($(ACCV),)
  INETS_FLAGS += -Dhttpd_acceptor_verbosity=$(ACCV)
else
  INETS_FLAGS += -Dhttpd_acceptor_verbosity=trace
endif

ifneq ($(AUTHV),)
  INETS_FLAGS += -Dhttpd_auth_verbosity=$(AUTHV)
else
  INETS_FLAGS += -Dhttpd_auth_verbosity=log
endif

ifneq ($(SECV),)
  INETS_FLAGS += -Dhttpd_security_verbosity=$(SECV)
else
  INETS_FLAGS += -Dhttpd_security_verbosity=log
endif


ifeq ($(INETS_ROOT),)
INETS_ROOT = ..
endif

MODULES =                 \
        inets_test_server \
	inets_test_lib    \
	httpd_test_lib    \
	inets_SUITE       \
        inets_app_test    \
        inets_appup_test  \
        httpd_test        \
        httpc_test        \
        ftp_test          \
        httpd_poll        \
        httpd_time_test

EBIN = .

HRL_FILES = 

ERL_FILES = $(MODULES:%=%.erl)

TARGET_FILES = $(MODULES:%=$(EBIN)/%.$(EMULATOR))

INETS_SUITE = inets_SUITE
FTP_SUITE   = ftp_SUITE


# ----------------------------------------------------
# FLAGS
# ----------------------------------------------------
ERL_COMPILE_FLAGS += $(FTP_FLAGS) $(INETS_FLAGS) 


# ----------------------------------------------------
# Targets
# ----------------------------------------------------

tests debug opt: $(TARGET_FILES)

clean:
	rm -f $(TARGET_FILES)
	rm -f core *~

docs:


# ----------------------------------------------------
# inets
# ---------------------------------------------------- 

include suite_targets.mk

info:
	@echo "INETS_DATA_DIR    = $(INETS_DATA_DIR)"
	@echo "INETS_PRIV_DIR    = $(INETS_PRIV_DIR)"
	@echo "INETS_SSL_LIB_DIR = $(INETS_SSL_LIB_DIR)"
	@echo "INETS_FLAGS       = $(INETS_FLAGS)"
	@echo "FTP_FLAGS         = $(FTP_FLAGS)"
