#  
# Makefile.src for ts, which makes the substitutions.
#
SSL_LIB_DIR = @ssl_libdir@
TARGET = @target@
SSLEAY_LIB = @SSLEAY_ROOT@/lib
all: copy_files make

copy_files:
	@erl_name@ -compile copy_files
	@erl_name@ -noshell -run copy_files start $(SSL_LIB_DIR) $(SSLEAY_LIB) $(TARGET)

make:
	cd obj
	-nmake
	-(cd obj; $(MAKE))

