%%% This file was automatically generated by snmp_mib_to_hrl v3.0
%%% Date: 01-Jun-2001::09:31:36
-ifndef('OTP-TC').
-define('OTP-TC', true).

-define(otpTcModule, [1,3,6,1,4,1,193,19,1,1,2]).

%% Range values


%% Default values

-endif.
