%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_File
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-11-05_12/otp_src_R12B-5/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.19
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_FILE_HRL).
-define(COSFILETRANSFER_FILE_HRL, true).




-endif.


