%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Resource
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b02.2009-09-21_11/otp_src_R13B02/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.22
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_RESOURCE_HRL).
-define(COSTRANSACTIONS_RESOURCE_HRL, true).




-endif.


