%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: ETraP_Server
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13a.2009-03-16_22/otp_src_R13A/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ETRAP_SERVER_HRL).
-define(ETRAP_SERVER_HRL, true).




-endif.


