%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTransactions
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-11-05_12/otp_src_R12B-5/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.19
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTRANSACTIONS_HRL).
-define(OE_COSTRANSACTIONS_HRL, true).




-endif.


