%%% This file was automatically generated by snmpc_mib_to_hrl version 4.13
%%% Date: 16-Mar-2009::22:51:09
-ifndef('OTP-TC').
-define('OTP-TC', true).

%% Oids

-define(otpTcModule, [1,3,6,1,4,1,193,19,1,1,2]).


%% Range values


%% Default values

-endif.
