%%% This file was automatically generated by snmpc_mib_to_hrl version 4.13.3
%%% Date: 07-Jun-2009::21:07:21
-ifndef('OTP-REG').
-define('OTP-REG', true).

%% Oids

-define(ericsson, [1,3,6,1,4,1,193]).

-define(otp, [1,3,6,1,4,1,193,19]).

-define(otpReg, [1,3,6,1,4,1,193,19,1]).

-define(otpModules, [1,3,6,1,4,1,193,19,1,1]).

-define(otpRegModule, [1,3,6,1,4,1,193,19,1,1,1]).

-define(otpGeneric, [1,3,6,1,4,1,193,19,2]).

-define(otpApplications, [1,3,6,1,4,1,193,19,3]).

-define(otpCaps, [1,3,6,1,4,1,193,19,4]).

-define(otpReqs, [1,3,6,1,4,1,193,19,5]).

-define(otpExpr, [1,3,6,1,4,1,193,19,6]).

-define(ssl, [1,3,6,1,4,1,193,19,10]).


%% Range values


%% Default values

-endif.
