%%% This file was automatically generated by snmpc_mib_to_hrl version 4.10.3
%%% Date: 07-Apr-2008::20:31:52
-ifndef('OTP-TC').
-define('OTP-TC', true).

%% Oids

-define(otpTcModule, [1,3,6,1,4,1,193,19,1,1,2]).


%% Range values


%% Default values

-endif.
