%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertiesIterator
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13a.2009-03-16_22/otp_src_R13A/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTIESITERATOR_HRL).
-define(COSPROPERTYSERVICE_PROPERTIESITERATOR_HRL, true).




-endif.


