%% This file is generated by gsb_run:rc2erl/1
-module(color_editor_ui). 
-copyright('Copyright (c) 1991-97 Ericsson Telecom AB').
-vsn('$Revision: /main/release/2 $').
-export([start/1]). 

start(GsParent) -> 
  gs:create(window, window, GsParent, [{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,true},{enter,false},{height,317},{iconname,color},{keypress,false},{leave,false},{map,false},{motion,false},{setfocus,false},{title,color},{width,380}]),
  gs:create(frame, frame1, window, [{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,false},{enter,false},{height,317},{keypress,false},{leave,false},{motion,false},{setfocus,false},{width,380},{x,0},{y,0}]),
  gs:create(button, cancel, frame1, [{align,center},{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{click,true},{configure,false},{data,[]},{destroy,false},{enable,true},{enter,false},{fg,black},{height,30},{justify,center},{keypress,false},{label,{text,[67,97,110,99,101,108]}},{leave,false},{setfocus,false},{underline,-1},{width,100},{x,270},{y,50}]),
  gs:create(button, ok, frame1, [{align,center},{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{click,true},{configure,false},{data,[]},{destroy,false},{enable,true},{enter,false},{fg,black},{height,30},{justify,center},{keypress,false},{label,{text,[79,107]}},{leave,false},{setfocus,false},{underline,-1},{width,100},{x,270},{y,10}]),
  gs:create(frame, test, frame1, [{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,false},{enter,false},{height,130},{keypress,false},{leave,false},{motion,false},{setfocus,false},{width,120},{x,140},{y,10}]),
  gs:create(listbox, lb, frame1, [{bc,{232,227,220}},{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{click,true},{configure,false},{data,[]},{destroy,false},{doubleclick,false},{enter,false},{fg,black},{height,130},{hscroll,false},{items,[]},{keypress,false},{leave,false},{motion,false},{scrollbg,{232,227,220}},{scrollfg,{232,227,220}},{selection,0},{selectmode,single},{setfocus,false},{vscroll,right},{width,120},{x,10},{y,10}]). 
