%% This file is generated by gsb_run:rc2erl/1
-module(file_dialog_ui). 
-copyright('Copyright (c) 1991-97 Ericsson Telecom AB').
-vsn('$Revision: /main/release/2 $').
-export([start/1]). 

start(GsParent) -> 
  gs:create(window, win, GsParent, [{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,true},{enter,false},{height,331},{iconname,file_dialog},{keypress,false},{leave,false},{map,true},{motion,false},{setfocus,false},{title,[70,105,108,101,32,100,105,97,108,111,103]},{width,305}]),
  gs:create(frame, frame1, win, [{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,false},{enter,false},{height,330},{keypress,false},{leave,false},{motion,false},{setfocus,false},{width,303},{x,0},{y,0}]),
  gs:create(button, cancel, frame1, [{align,center},{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{click,true},{configure,false},{data,[]},{destroy,false},{enable,true},{enter,false},{fg,black},{height,30},{justify,center},{keypress,false},{label,{text,[67,97,110,99,101,108]}},{leave,false},{setfocus,false},{underline,-1},{width,90},{x,200},{y,50}]),
  gs:create(button, ok, frame1, [{align,center},{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{click,true},{configure,false},{data,[]},{destroy,false},{enable,true},{enter,false},{fg,black},{height,30},{justify,center},{keypress,false},{label,{text,[79,107]}},{leave,false},{setfocus,false},{underline,-1},{width,93},{x,200},{y,10}]),
  gs:create(label, label, frame1, [{align,nw},{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,false},{enter,false},{fg,black},{height,30},{justify,center},{keypress,false},{label,{text,[]}},{leave,false},{motion,false},{setfocus,false},{underline,-1},{width,252},{x,10},{y,290}]),
  gs:create(listbox, lb, frame1, [{bc,{232,227,220}},{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{click,true},{configure,false},{data,[]},{destroy,false},{doubleclick,true},{enter,false},{fg,black},{height,190},{hscroll,true},{items,[]},{keypress,false},{leave,false},{motion,false},{scrollbg,{232,227,220}},{scrollfg,{232,227,220}},{selection,0},{selectmode,single},{setfocus,false},{vscroll,right},{width,183},{x,10},{y,90}]),
  gs:create(entry, entry, frame1, [{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,false},{enable,true},{enter,false},{fg,black},{height,30},{keypress,true},{leave,false},{motion,false},{setfocus,false},{width,183},{x,10},{y,50}]),
  gs:create(label, label1, frame1, [{align,nw},{bg,{232,227,220}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,false},{enter,false},{fg,black},{height,30},{justify,center},{keypress,false},{label,{text,[115,101,108,101,99,116,105,111,110]}},{leave,false},{motion,false},{setfocus,false},{underline,-1},{width,130},{x,10},{y,10}]). 
