%% This file is generated by gsb_run:rc2erl/1
-module(save_soft_dialog_ui). 
-copyright('Copyright (c) 1991-97 Ericsson Telecom AB').
-vsn('$Revision: /main/release/2 $').
-export([start/1]). 

start(GsParent) -> 
  gs:create(window, win, GsParent, [{bg,{217,217,217}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,true},{enter,false},{height,90},{iconbitmap,[]},{iconmask,[]},{iconname,[83,97,118,101,32,97,115,32,115,111,102,116,119,105,100,103,101,116]},{keypress,false},{keyrelease,false},{leave,false},{map,true},{motion,false},{title,[83,97,118,101,32,97,115,32,115,111,102,116,119,105,100,103,101,116]},{width,390}]),
  gs:create(label, label1, win, [{align,w},{bg,{217,217,217}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,false},{enter,false},{fg,black},{focus,false},{height,30},{justify,left},{keypress,false},{keyrelease,false},{label,{text,[77,111,100,117,108,101,58]}},{leave,false},{motion,false},{underline,-1},{width,60},{x,10},{y,10}]),
  gs:create(label, label2, win, [{align,w},{bg,{217,217,217}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,false},{enter,false},{fg,black},{focus,false},{height,30},{justify,left},{keypress,false},{keyrelease,false},{label,{text,[69,120,112,111,114,116,115,58]}},{leave,false},{motion,false},{underline,-1},{width,60},{x,10},{y,50}]),
  gs:create(entry, entry_module, win, [{bg,{217,217,217}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,false},{enter,false},{fg,black},{focus,false},{height,30},{justify,left},{keypress,true},{keyrelease,false},{leave,false},{motion,false},{text,[]},{width,200},{x,70},{y,9}]),
  gs:create(entry, entry_exports, win, [{bg,{217,217,217}},{buttonpress,false},{buttonrelease,false},{configure,false},{data,[]},{destroy,false},{enter,false},{fg,black},{focus,false},{height,30},{justify,left},{keypress,true},{keyrelease,false},{leave,false},{motion,false},{text,[]},{width,200},{x,70},{y,52}]),
  gs:create(button, ok, win, [{align,center},{bg,{217,217,217}},{buttonpress,false},{buttonrelease,false},{click,true},{configure,false},{data,[]},{destroy,false},{enter,false},{fg,black},{focus,false},{height,30},{justify,left},{keypress,false},{label,{text,[79,107]}},{leave,false},{motion,false},{underline,-1},{width,100},{x,283},{y,9}]),
  gs:create(button, cancel, win, [{align,center},{bg,{217,217,217}},{buttonpress,false},{buttonrelease,false},{click,true},{configure,false},{data,[]},{destroy,false},{enter,false},{fg,black},{focus,false},{height,30},{justify,left},{keypress,false},{label,{text,[67,97,110,99,101,108]}},{leave,false},{motion,false},{underline,-1},{width,100},{x,283},{y,52}]). 
