%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventDomainAdmin_EventDomain
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b01.2009-06-07_20/otp_src_R13B01/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.2.21
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTDOMAINADMIN_EVENTDOMAIN_HRL).
-define(COSEVENTDOMAINADMIN_EVENTDOMAIN_HRL, true).




-endif.


