#=============================================================================
#
#    File:  lib/dialyzer/Makefile
# Authors:  Kostis Sagonas and Tobias Lindahl
#
#=============================================================================
include $(ERL_TOP)/make/target.mk
include $(ERL_TOP)/make/$(TARGET)/otp.mk

#
# Macros
#

SUB_DIRECTORIES = src doc/src

include vsn.mk
VSN = $(DIALYZER_VSN)

SPECIAL_TARGETS =

#
# Default Subdir Targets
#
include $(ERL_TOP)/make/otp_subdir.mk

