%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: OrberApp_IFR
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b01.2009-06-07_20/otp_src_R13B01/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.2.21
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ORBERAPP_IFR_HRL).
-define(ORBERAPP_IFR_HRL, true).




-endif.


