%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: OrberApp
%% Source: /ldisk/daily_build/otp_prebuild_r12b.2008-11-05_12/otp_src_R12B-5/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.2.19
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ORBERAPP_HRL).
-define(ORBERAPP_HRL, true).




-endif.


