%% Generated by the Erlang ASN.1 compiler version:1.4.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module OrberCSIv2



-record('AttributeCertChain',{
attributeCert, certificateChain}).

-define('gssup-mechanism', {2,23,130,1,1,1}).
-define('scoped-username', {2,23,130,1,2,1}).
