%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: StackModule
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r13b02.2009-09-21_11/otp_src_R13B02/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.2.22
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(STACKMODULE_HRL).
-define(STACKMODULE_HRL, true).


-record('StackModule_EmptyStack', {'OE_ID'="IDL:StackModule/EmptyStack:1.0"}).


-endif.


