%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: StackModule_Stack
%% Source: /ldisk/daily_build/otp_prebuild_r11b.2007-06-11_19/otp_src_R11B-5/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.2.13
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(STACKMODULE_STACK_HRL).
-define(STACKMODULE_STACK_HRL, true).




-endif.


