%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: StackModule
%% Source: /net/shelob/ldisk/daily_build/otp_prebuild_r13b.2009-04-15_20/otp_src_R13B/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.2.20
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(STACKMODULE_HRL).
-define(STACKMODULE_HRL, true).


-record('StackModule_EmptyStack', {'OE_ID'="IDL:StackModule/EmptyStack:1.0"}).


-endif.


