#
# Invoke with GNU make or clearmake -C gnu.
#

ifneq ($(TARGET),win32)

include $(ERL_TOP)/make/run_make.mk

else

# Nothing to do here for win32...

%:
	@echo Nothing to do for "'"$@"'" on $(TARGET)
endif
